config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#login'
  get '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'

  post 'message', to: 'messages#create'

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  validates :body, presence: true, length:{maximum: 250 }

  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, uniqueness: true, length:{minimum: 4, maximum: 25}, presence: true

  has_many :messages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in!"
      redirect_to login_path
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      ActionCable.server.broadcast "chatroom_channel",
                                    {msg: message_partial(@message)}
    end
  end

  private
  def message_params
    params.require(:message).permit(:body)
  end

  def message_partial (message)
    render(partial: 'shared/message', locals: {obj: message})
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :require_user, only: [:home]

  def home
    @messages = Message.all
    @message = Message.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:login, :create]

  def login
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome #{user.username}"
      redirect_to root_path
    else
      flash[:danger] = "Sorry no user found with those credentials!"
      render 'login'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out! Goodbye"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:danger] = "Already logged in!"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_menu.haml
.ui.secondary.pointing.menu
  = link_to 'Chat', root_path, class: 'item'
  %a.item
    Messages
  %a.item
    Friends
  .ui.dropdown.item
    Drop Down
    %i.dropdown.icon
    .menu
      %a.item Chat
      %a.item About


  .right.menu
    - if !logged_in?
      =link_to 'Login', login_path, class: 'ui item'
    - else
      = link_to 'Log out', logout_path, class: 'ui item'

    %a.ui.item
      %button.ui.primary.button Sign Up

app/views/layouts/_messages.haml
- flash.each do |type, msg|
  .ui.message{ class: [("success" if type == 'success'),("negative" if type == 'danger')]}
    %i.close.icon
    .header
      = msg

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HChat</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/menu' %>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_message_form.haml
= form_for(@message, class: 'ui reply form', url: message_path, remote: true) do |f|
  .ui.fluid.icon.input#msg_input
    = f.text_field :body
    = f.button '<i class="inverted edit icon"></i>'.html_safe, class: 'ui teal button', id: 'send-btn'

app/views/pages/home.html.haml
.ui.equal.width.grid
  -# .row
  -#   .two.wide.column
  -#     %h1.ui.icon.header
  -#       %i.blue.quinscape.icon
  .row
    .column
      .ui.equal.width.grid
        .row
          .ten.wide.column
            .ui.fluid.blue.card.chatbox
              .content#messages
                .ui.small.feed#msg-container
                  %h4.ui.header Followers Activity
                  - @messages.each do |msg|
                    =render 'shared/message', obj: msg

              .extra-content
                = render 'message_form'

          .column
            .ui.vertical.text.menu
              .header.item Friends
              %a.active.item
                Closest
              %a.item
                Most Comments
              %a.item
                Most Popular

app/views/shared/_message.haml
.event
  .content
    .summary
      %a= obj.user.username
      %a.msg_body= obj.body